/**
 * KNOCH-005 — Hero Section: Film-Counter Loader + Reveal Sequence
 *
 * Execution order:
 *   1. DOM ready: set #chrome opacity 0 + add body.loader-active
 *   2. window.load: run film-counter loader (1.8s tween + progress bar)
 *   3. After ~2s: fade out loader, call initLenis(), run hero reveal timeline
 *   4. After reveal: set up ScrollTrigger exit animations
 *
 * Why window.load (not DOMContentLoaded)?
 *   We want the loader to genuinely cover the hero image loading. On fast
 *   cached connections the 2s minimum still plays for cinematic effect.
 *
 * Why import initLenis here instead of main.js?
 *   Lenis must not start until after the loader — if Lenis initialised before
 *   the loader finished, ScrollTrigger would set up proxies against a page
 *   whose hero image might not be loaded, and the user could scroll during
 *   the intro. Calling initLenis() here in onComplete guarantees correct order.
 */

import gsap from 'gsap';
import ScrollTrigger from 'gsap/ScrollTrigger';
import { initLenis } from './lenis.js';

gsap.registerPlugin(ScrollTrigger);

/* All six reel stills, in cycle order. The first entry (reel-01) is
   the loader/reveal frame so the visible state during the intro matches
   what the slideshow will resume on after the reveal completes.
   KNOCH-019: paths point at the .webp siblings generated by
   scripts/optimize-images.mjs - the source .png/.jpg files stay in
   /assets/reel/ as fallbacks but the slideshow loads .webp directly
   for ~95% byte savings (reel-01 1.96 MB -> 39.6 KB). WebP support is
   universal in 2026 (Safari 14+, all Chromium, Firefox 65+) so a
   runtime detection branch isn't needed here. */
const HERO_SLIDESHOW_IMAGES = [
  '/assets/reel/reel-01.webp',
  '/assets/reel/reel-02.webp',
  '/assets/reel/reel-03.webp',
  '/assets/reel/reel-04.webp',
  '/assets/reel/reel-05.webp',
  '/assets/reel/reel-06.webp',
];

/* Editorial film-slate label for each slide. Index aligns with
   HERO_SLIDESHOW_IMAGES above. Swapped in sync with the bg crossfade
   so the meta caption always describes what the visitor is looking
   at. To retitle a slide, edit one line here - no other code change.

   Mapped from the actual reel imagery:
     01  studio portrait silhouette          - "A QUIET PORTRAIT"
     02  cellist at an anniversary / worship - "A NIGHT OF WORSHIP"
                                                gathering
     03  Nigerian introduction ceremony      - "A NIGERIAN INTRODUCTION"
     04  outdoor woods wedding (triangle arch)- "A WEDDING IN MAY"
     05  B&W wedding recessional, the couple - "HUSBAND AND WIFE"
     06  Mont Alto Woodsmen competition      - "THE WOODSMEN"

   Format mirrors the existing markup default: bracketed mono caps
   with an em-dash separator. Keep <22 chars after the dash so the
   label fits the hero-meta line on narrow viewports. */
const HERO_SLIDESHOW_META = [
  '[ FILM 01 — A QUIET PORTRAIT ]',
  '[ FILM 02 — A NIGHT OF WORSHIP ]',
  '[ FILM 03 — A NIGERIAN INTRODUCTION ]',
  '[ FILM 04 — A WEDDING IN MAY ]',
  '[ FILM 05 — HUSBAND AND WIFE ]',
  '[ FILM 06 — THE WOODSMEN ]',
];

const SLIDE_HOLD_MS  = 5500;  // time each slide stays at full opacity
const SLIDE_FADE_S   = 1.6;   // crossfade duration (seconds)

/* Slide refs — populated inside initHero() so they exist before the reveal
   timeline runs, consumed by _onLoaderComplete() to start the cycle. */
let _heroSlides = null;

/* Build the slideshow layer stack inside .hero-bg. Returns the slide
   elements in cycle order, with slide[0] starting at opacity 1 so the
   loader/reveal sequence can scale it up (transform on the parent .hero-bg
   composites cleanly with the child opacity tweens here).
   Called early in initHero() so the layers exist before the reveal timeline
   triggers — otherwise the bg would be blank during scale(1.1)→scale(1). */
function _buildHeroSlides(heroBg) {
  const slides = HERO_SLIDESHOW_IMAGES.map((url, i) => {
    const slide = document.createElement('div');
    slide.className = 'hero-slide';
    slide.style.backgroundImage = `url('${url}')`;
    if (i === 0) slide.style.opacity = '1';
    heroBg.appendChild(slide);
    return slide;
  });
  return slides;
}

/* Slideshow loop — cycles through the slide layers with a crossfade,
   pulsing the parent's --slide-blur and --slide-bright during the swap so
   the transition reads as a soft "rack focus" rather than a hard cut.
   Pauses while the document is hidden (Page Visibility API) to avoid
   playing through wasted swaps if the user tabs away mid-cycle. */
function _runHeroSlideshow(heroBg, slides) {
  if (!slides.length || slides.length < 2) return;

  /* The hero-meta caption is swapped in sync with the bg crossfade so
     the editorial slate always describes what the visitor is looking at.
     Optional - if the element is missing (defensive against future
     markup edits) the slideshow still cycles images. */
  const heroMeta = document.querySelector('.hero-meta');

  let current = 0;
  let timer   = null;

  const advance = () => {
    const next = (current + 1) % slides.length;

    /* Crossfade the two layers in parallel. inOut on both halves so the
       midpoint of the swap is also the midpoint of the blur/brightness
       pulse — peaks line up perceptually as one event. */
    gsap.to(slides[current], {
      opacity: 0,
      duration: SLIDE_FADE_S,
      ease: 'power2.inOut',
    });
    gsap.to(slides[next], {
      opacity: 1,
      duration: SLIDE_FADE_S,
      ease: 'power2.inOut',
    });

    /* Filter pulse on the parent — blur peaks at the crossfade midpoint
       and the brightness lifts slightly so the swap feels like a film
       projector dissolve instead of a flat fade. yoyo: true brings both
       props back to their resting values, repeat: 1 = one out + one back. */
    gsap.to(heroBg, {
      '--slide-blur': '2.4px',
      '--slide-bright': 0.55,
      duration: SLIDE_FADE_S * 0.5,
      ease: 'sine.inOut',
      yoyo: true,
      repeat: 1,
      overwrite: 'auto',
    });

    /* Hero-meta caption swap — fade out (~40% of crossfade), set new
       text at the midpoint, fade back in. Lands the new label right
       around the time the new bg image hits full opacity, so the
       caption and the image transition feel like one event rather
       than two. Guarded against missing meta data (returns null in
       a future-edge case where the arrays drift out of sync). */
    const nextMeta = HERO_SLIDESHOW_META[next];
    if (heroMeta && nextMeta) {
      gsap.to(heroMeta, {
        opacity: 0,
        duration: SLIDE_FADE_S * 0.4,
        ease: 'power2.in',
        onComplete: () => {
          heroMeta.textContent = nextMeta;
          gsap.to(heroMeta, {
            opacity: 1,
            duration: SLIDE_FADE_S * 0.6,
            ease: 'power2.out',
          });
        },
      });
    }

    current = next;
  };

  const start = () => {
    if (timer) return;
    timer = setInterval(advance, SLIDE_HOLD_MS);
  };
  const stop = () => {
    clearInterval(timer);
    timer = null;
  };

  start();

  /* Cheap power saver — pause the cycle when the tab is hidden.
     visibilitychange fires reliably across modern browsers; no need to
     also handle pageshow/pagehide. */
  document.addEventListener('visibilitychange', () => {
    if (document.hidden) stop(); else start();
  });
}

export function initHero() {
  // ── 1. Pre-loader DOM state ────────────────────────────────────────────

  // Clip hero headline lines immediately — fromTo at t=0.2 in _onLoaderComplete
  // doesn't apply the from-state until the playhead reaches that offset, so
  // without this set() the text is briefly visible during the loader.
  gsap.set(document.querySelectorAll('.hero-headline .line > span'), { y: '110%' });

  // Hide chrome until loader completes — prevents nav flashing in before the
  // intro sequence has run. Faded back in inside loader onComplete.
  const chrome = document.querySelector('#chrome');
  if (chrome) chrome.style.opacity = '0';

  // Hide cursor during load — .loader-active CSS rule sets opacity 0
  document.body.classList.add('loader-active');

  // ── 2. Element references ──────────────────────────────────────────────

  const loader        = document.getElementById('loader');
  const counterEl     = document.querySelector('.loader-counter');
  const progressFill  = document.querySelector('.loader-progress-fill');

  const heroBg        = document.querySelector('.hero-bg');
  const heroMeta      = document.querySelector('.hero-meta');
  const heroSub       = document.getElementById('hero-sub');

  /* Set the initial slate label to match slide 0 - the HTML markup
     ships with a sensible default but the data lives here, in
     HERO_SLIDESHOW_META, so any retitle is a one-line edit. The
     label is currently opacity:0 (set in CSS); the reveal timeline
     fades it in along with the rest of the hero. */
  if (heroMeta && HERO_SLIDESHOW_META[0]) {
    heroMeta.textContent = HERO_SLIDESHOW_META[0];
  }

  /* Build the slideshow layers immediately so they exist before the reveal
     scale tween runs. Stored at module scope (_heroSlides) so
     _onLoaderComplete can start the cycle once the reveal finishes. */
  if (heroBg) _heroSlides = _buildHeroSlides(heroBg);

  // Guard: if critical loader elements are missing, skip gracefully
  if (!loader || !counterEl || !progressFill) {
    console.warn('[KNOCH-005] Loader elements missing — skipping loader animation');
    _onLoaderComplete();
    return;
  }

  // ── Hero BG cursor parallax (fine-pointer / desktop only) ─────────────
  // x/y pixels compose with the scroll-exit yPercent without conflict —
  // GSAP tracks each transform component independently.
  if (heroBg && !window.matchMedia('(pointer: coarse)').matches) {
    const heroEl = document.getElementById('hero');
    if (heroEl) {
      heroEl.addEventListener('mousemove', (e) => {
        const rect = heroEl.getBoundingClientRect();
        const xRel = (e.clientX - rect.left) / rect.width  - 0.5;
        const yRel = (e.clientY - rect.top)  / rect.height - 0.5;
        gsap.to(heroBg, {
          x: xRel * 20,
          y: yRel * 12,
          duration: 1.8,
          ease: 'power2.out',
          overwrite: 'auto',
        });
      }, { passive: true });

      heroEl.addEventListener('mouseleave', () => {
        gsap.to(heroBg, { x: 0, y: 0, duration: 2.2, ease: 'power2.out', overwrite: 'auto' });
      }, { passive: true });
    }
  }

  // ── 3. Run loader on window.load ───────────────────────────────────────

  window.addEventListener('load', () => {
    // Proxy object for the counter tween — GSAP can only tween numeric
    // properties, so we wrap the display value in an object and update
    // the DOM in onUpdate. Math.ceil ensures we always show whole numbers
    // and that 00 is only shown at the very start (val = 0 → ceil(0) = 0).
    const proxy = { val: 0 };

    // Film-frame counter: 00 → 36 over 1.8s, power2.inOut
    gsap.to(proxy, {
      val: 36,
      duration: 1.8,
      ease: 'power2.inOut',
      onUpdate() {
        // padStart(2,'0') keeps the two-digit display at all times
        counterEl.textContent = String(Math.ceil(proxy.val)).padStart(2, '0');
      },
      onComplete() {
        // Ensure counter lands exactly on '36'
        counterEl.textContent = '36';
      },
    });

    // Progress bar fill: width 0% → 100% in 1.8s, power2.inOut
    // Timed to match the counter exactly so both finish together.
    gsap.to(progressFill, {
      width: '100%',
      duration: 1.8,
      ease: 'power2.inOut',
    });

    // ── 4. Fade out loader after 2s total ─────────────────────────────
    // 2s = 1.8s tween + 0.2s pause to let the counter land on 36.
    // autoAlpha handles visibility + opacity atomically — this prevents
    // the invisible loader from capturing pointer events after fade.
    gsap.to(loader, {
      autoAlpha: 0,
      duration: 1,
      delay: 2,
      ease: 'power2.inOut',
      onComplete() {
        // Remove from layout entirely
        loader.style.display = 'none';

        // Start Lenis smooth scroll (must happen before ScrollTrigger
        // animations so the proxy is live when they register)
        initLenis();

        // Show cursor
        document.body.classList.remove('loader-active');

        // Fade chrome back in
        gsap.to('#chrome', {
          opacity: 1,
          duration: 0.8,
          delay: 0.2,
        });

        // Run hero reveal and scroll-exit setup
        _onLoaderComplete();
      },
    });
  });
}

// ── 5. Hero reveal sequence ────────────────────────────────────────────────

/**
 * Builds and plays the reveal GSAP timeline immediately after the loader fades.
 * Timeline positions (all relative to t=0):
 *   t=0.0 — hero-bg scale 1.1→1 (2.4s, power3.out)
 *   t=0.0 — hero-meta fade in (0.8s)
 *   t=0.2 — headline line spans translateY(110%→0), stagger 0.12s
 *   t=1.4 — #hero-sub fade in
 */
function _onLoaderComplete() {
  const heroBg       = document.querySelector('.hero-bg');
  const heroMeta     = document.querySelector('.hero-meta');
  const heroSub      = document.getElementById('hero-sub');

  /* Use > span (direct child) so .char-hover spans added by char-hover.js
     inside the wrapper span are not matched — they have no initial offset
     and should not participate in the line reveal. */
  const lineSpans = document.querySelectorAll('.hero-headline .line > span');

  const tl = gsap.timeline();

  // Bg scale-down
  if (heroBg) {
    tl.to(heroBg, {
      scale: 1,
      duration: 2.4,
      ease: 'power3.out',
    }, 0);
  }

  // Meta label fade in
  if (heroMeta) {
    tl.to(heroMeta, {
      opacity: 1,
      duration: 0.8,
      ease: 'power2.out',
    }, 0);
  }

  // Headline clip-reveal — initial y:'110%' is pre-set by gsap.set() in initHero()
  // so we only need a to() here. fromTo at a non-zero timeline offset doesn't
  // apply the from-state until the playhead reaches it, causing a brief flash.
  if (lineSpans.length) {
    tl.to(lineSpans,
      { y: 0, duration: 1.2, ease: 'expo.out', stagger: 0.12 },
      0.2
    );
  }

  // ── Film-grain dissolve on per-character spans (KNOCH-030) ──────────────
  // char-hover.js has already split the headline into .char-hover spans.
  // We animate the shared SVG filter (feTurbulence displacement) from high
  // distortion to zero while staggering each char's opacity from 0 → 1.
  // This creates the effect of characters being "developed" through grain.
  const grainChars  = document.querySelectorAll('.hero-headline .char-hover');
  const turbulence  = document.getElementById('grain-turbulence');
  const displace    = document.getElementById('grain-displace');

  if (grainChars.length && turbulence && displace) {
    const prefersReduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

    if (prefersReduced) {
      // Instant reveal — skip grain animation
      grainChars.forEach(ch => {
        ch.style.opacity = '1';
        ch.classList.add('grain-revealed');
      });
    } else {
      // Set initial displacement intensity high
      displace.setAttribute('scale', '55');
      turbulence.setAttribute('baseFrequency', '0.065');

      // Animate SVG filter dissolution — shared across all chars
      tl.to({}, {
        duration: 1.8,
        ease: 'power2.out',
        onUpdate: function () {
          const p = this.progress();
          const scale = 55 * (1 - p);
          const freq  = 0.065 * (1 - p * 0.8);
          displace.setAttribute('scale', scale.toFixed(1));
          turbulence.setAttribute('baseFrequency', freq.toFixed(4));
        },
        onComplete: () => {
          displace.setAttribute('scale', '0');
        },
      }, 0.3);

      // Stagger char opacity — each char fades in as grain dissolves
      tl.to(grainChars, {
        opacity: 1,
        duration: 0.9,
        ease: 'power2.out',
        stagger: { from: 'start', amount: 0.8 },
        onComplete: () => {
          // Hand filter control back to char-hover.js
          grainChars.forEach(ch => {
            ch.classList.add('grain-revealed');
            ch.style.filter = '';
          });
        },
      }, 0.3);
    }
  }

  // Sub text fade in
  if (heroSub) {
    tl.to(heroSub, {
      opacity: 1,
      duration: 0.8,
      ease: 'power2.out',
    }, 1.4);
  }

  // Set up scroll-exit triggers once the reveal completes
  tl.call(_setupScrollExit);

  /* Start the reel slideshow after the reveal finishes. Fires from inside
     the reveal timeline so the first crossfade lands well after reel-01
     has had time to settle into place. prefers-reduced-motion users skip
     it entirely — the static reel-01 stays visible. */
  if (heroBg && _heroSlides && !window.matchMedia('(prefers-reduced-motion: reduce)').matches) {
    tl.call(() => _runHeroSlideshow(heroBg, _heroSlides));
  }
}

// ── 6. Hero exit on scroll (ScrollTrigger) ─────────────────────────────────

/**
 * Parallax exit for hero on scroll.
 * Two simultaneous ScrollTrigger animations share the same trigger range:
 *   • .hero-bg:      yPercent 0 → 25 (parallax — bg moves slower than page)
 *   • .hero-content: yPercent 0 → -40 + opacity 1 → 0 (content lifts + fades)
 *
 * scrub: true = animation position is directly tied to scroll offset,
 * giving the user 1:1 control over the parallax speed.
 *
 * Called as a .call() inside the reveal timeline so it only registers
 * after the reveal completes — prevents ScrollTrigger firing before
 * the hero is fully revealed.
 */
function _setupScrollExit() {
  const heroBg      = document.querySelector('.hero-bg');
  const heroContent = document.querySelector('.hero-content');

  const triggerConfig = {
    trigger: '#hero',
    start: 'top top',
    end: 'bottom top',
    scrub: true,
  };

  // Background parallax — moves upward at 25% of scroll speed
  if (heroBg) {
    gsap.to(heroBg, {
      yPercent: 25,
      ease: 'none', // linear scrub — easing should come from scroll inertia
      scrollTrigger: triggerConfig,
    });
  }

  // Content exit — lifts and fades simultaneously
  if (heroContent) {
    gsap.to(heroContent, {
      yPercent: -40,
      opacity: 0,
      ease: 'none',
      scrollTrigger: triggerConfig,
    });
  }
}
